### ISSUE TITLE
Bug with conf/nginx/nginx-site.conf

### ISSUE THREAD

**Issue by graymic** [ngineered/nginx-php-fpm#112]
When in the **root** of a project, if you create the `conf/nginx/nginx-site*.conf`

If you were to add anything:

```
server {
   # configuration
}
```

Typically the EOF is missing when copied into the container upon performing a `docker-compose up -d` this yield an nginx critical error. I found this after a while of hunting through `/etc/nginx/sites-available/`

My own workaround within compose thus far has been:

```
services:
  volumes_source:
      image: tianon/true
      volumes:
          - ./configuration/nginx/sites:/etc/nginx/sites-available
          - ./src:/var/www/html

  php-nginx:
    image: richarvey/nginx-php-fpm
    ports:
      - "80:80"
      - "443:443"
    volumes_from:
      - volumes_source
```
